### ISSUE TITLE
Функция должна принимать на вход расход топлива и объём имеющегося топлива

### ISSUE THREAD

**Issue by coursar** [Muhammadnumon/rest_road#2]
https://github.com/Muhammadnumon/rest_road/blob/055639aa85af0daa5f49ace83b9a4f7cbaa6f1b5/main.go#L5

**Comment by Muhammadnumon** [comment]
@coursar 
https://github.com/Muhammadnumon/rest_road/blob/414045d91f6225bf4ddd97e385992bd14f0fb431/main.go#L5
Fixed #2 and #3 414045d91f6225bf4ddd97e385992bd14f0fb431
