### ISSUE TITLE
В чём смысл этой строки?

### ISSUE THREAD

**Issue by coursar** [Muhammadnumon/rest_road#3]
https://github.com/Muhammadnumon/rest_road/blob/055639aa85af0daa5f49ace83b9a4f7cbaa6f1b5/main.go#L7

**Comment by Muhammadnumon** [comment]
https://github.com/Muhammadnumon/rest_road/blob/414045d91f6225bf4ddd97e385992bd14f0fb431/main.go#L5
Fixed #2 414045d91f6225bf4ddd97e385992bd14f0fb431
